[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:apache]
command=/usr/sbin/apache2ctl -D FOREGROUND
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/apache.err.log
stdout_logfile=/var/log/supervisor/apache.out.log

[program:siapp_mqtt]
command=php /var/www/siapp/artisan mqtt:subscribe
directory=/var/www/siapp
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/siapp_mqtt.err.log
stdout_logfile=/var/log/supervisor/siapp_mqtt.out.log

[program:siapp_device]
command=php /var/www/siapp/artisan mqtt:device
directory=/var/www/siapp
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/siapp_device.err.log
stdout_logfile=/var/log/supervisor/siapp_device.out.log

[program:siapp_scheduler]
command=php /var/www/siapp/artisan schedule:work
directory=/var/www/siapp
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/siapp_scheduler.err.log
stdout_logfile=/var/log/supervisor/siapp_scheduler.out.log
